package com.feragusper.smokeanalytics.libraries.smokes.domain.model

/** One searchable emoji: the glyph plus lowercase keywords used to filter it. */
data class EmojiEntry(val emoji: String, val keywords: List<String>)

/**
 * A broad, searchable emoji catalog for the trigger icon picker. Not the entire Unicode set,
 * but wide enough across faces, food/drink, activities, objects, places, nature and symbols
 * that the search box feels complete for tagging triggers. Keywords drive [searchEmojis].
 */
val EmojiCatalog: List<EmojiEntry> = listOf(
    // Smileys & emotion
    EmojiEntry("😀", listOf("smile", "happy", "grin")),
    EmojiEntry("😁", listOf("grin", "smile", "happy")),
    EmojiEntry("😂", listOf("laugh", "lol", "tears", "funny")),
    EmojiEntry("🤣", listOf("laugh", "rofl", "funny")),
    EmojiEntry("😊", listOf("smile", "blush", "happy")),
    EmojiEntry("😇", listOf("angel", "innocent", "halo")),
    EmojiEntry("🙂", listOf("smile", "slight")),
    EmojiEntry("😉", listOf("wink")),
    EmojiEntry("😍", listOf("love", "heart eyes", "crush")),
    EmojiEntry("🥰", listOf("love", "adore", "hearts")),
    EmojiEntry("😘", listOf("kiss", "love")),
    EmojiEntry("😋", listOf("yum", "tasty", "food")),
    EmojiEntry("😎", listOf("cool", "sunglasses")),
    EmojiEntry("🤩", listOf("star", "excited", "wow")),
    EmojiEntry("🥳", listOf("party", "celebrate", "birthday")),
    EmojiEntry("😏", listOf("smirk")),
    EmojiEntry("😌", listOf("relieved", "calm", "content")),
    EmojiEntry("😔", listOf("sad", "pensive", "down")),
    EmojiEntry("😟", listOf("worried", "sad")),
    EmojiEntry("😕", listOf("confused", "unsure")),
    EmojiEntry("🙁", listOf("frown", "sad")),
    EmojiEntry("😣", listOf("persevere", "struggle")),
    EmojiEntry("😖", listOf("confounded", "stress", "frustrated")),
    EmojiEntry("😫", listOf("tired", "exhausted", "stress")),
    EmojiEntry("😩", listOf("weary", "tired", "stress")),
    EmojiEntry("🥺", listOf("pleading", "sad", "cute")),
    EmojiEntry("😢", listOf("cry", "sad", "tear")),
    EmojiEntry("😭", listOf("sob", "cry", "sad")),
    EmojiEntry("😤", listOf("angry", "frustrated", "steam")),
    EmojiEntry("😠", listOf("angry", "mad")),
    EmojiEntry("😡", listOf("rage", "angry", "mad")),
    EmojiEntry("🤬", listOf("swear", "angry", "curse")),
    EmojiEntry("😳", listOf("flushed", "embarrassed")),
    EmojiEntry("🥵", listOf("hot", "heat", "sweat")),
    EmojiEntry("🥶", listOf("cold", "freezing")),
    EmojiEntry("😰", listOf("anxious", "anxiety", "sweat", "nervous")),
    EmojiEntry("😨", listOf("fear", "scared", "anxiety")),
    EmojiEntry("😱", listOf("scream", "shock", "fear")),
    EmojiEntry("😥", listOf("sad", "relieved", "worried")),
    EmojiEntry("😓", listOf("sweat", "stress", "tired")),
    EmojiEntry("🤔", listOf("think", "hmm", "wonder")),
    EmojiEntry("🤨", listOf("skeptic", "doubt", "eyebrow")),
    EmojiEntry("😐", listOf("neutral", "meh")),
    EmojiEntry("😑", listOf("expressionless", "blank")),
    EmojiEntry("🙄", listOf("eyeroll", "annoyed")),
    EmojiEntry("😴", listOf("sleep", "tired", "zzz")),
    EmojiEntry("😪", listOf("sleepy", "tired")),
    EmojiEntry("🥱", listOf("yawn", "bored", "tired", "boredom")),
    EmojiEntry("😷", listOf("mask", "sick")),
    EmojiEntry("🤒", listOf("sick", "fever", "ill")),
    EmojiEntry("🤕", listOf("hurt", "injured")),
    EmojiEntry("🤢", listOf("nausea", "sick", "gross")),
    EmojiEntry("🤮", listOf("vomit", "sick")),
    EmojiEntry("🤯", listOf("mind blown", "shock", "stress")),
    EmojiEntry("🥴", listOf("woozy", "drunk", "dizzy")),
    EmojiEntry("😵", listOf("dizzy", "knocked out")),
    EmojiEntry("🤠", listOf("cowboy")),
    EmojiEntry("🫠", listOf("melt", "overwhelmed")),
    EmojiEntry("🫥", listOf("blank", "invisible")),
    EmojiEntry("🙃", listOf("upside down", "silly")),
    EmojiEntry("😬", listOf("grimace", "awkward")),
    EmojiEntry("🤐", listOf("zip", "quiet")),
    EmojiEntry("🤫", listOf("shh", "quiet", "secret")),
    EmojiEntry("🤥", listOf("lie", "pinocchio")),
    // Hearts & symbols
    EmojiEntry("❤️", listOf("heart", "love", "red")),
    EmojiEntry("🧡", listOf("heart", "orange")),
    EmojiEntry("💛", listOf("heart", "yellow")),
    EmojiEntry("💚", listOf("heart", "green")),
    EmojiEntry("💙", listOf("heart", "blue")),
    EmojiEntry("💜", listOf("heart", "purple")),
    EmojiEntry("🖤", listOf("heart", "black")),
    EmojiEntry("💔", listOf("broken heart", "sad")),
    EmojiEntry("💕", listOf("hearts", "love")),
    EmojiEntry("💖", listOf("sparkle heart", "love")),
    EmojiEntry("⭐", listOf("star", "favorite")),
    EmojiEntry("🌟", listOf("star", "glow", "shine")),
    EmojiEntry("✨", listOf("sparkles", "shine", "magic")),
    EmojiEntry("🔥", listOf("fire", "hot", "lit")),
    EmojiEntry("💥", listOf("boom", "explosion")),
    EmojiEntry("⚡", listOf("lightning", "energy", "fast")),
    EmojiEntry("💫", listOf("dizzy", "star")),
    EmojiEntry("💯", listOf("hundred", "perfect")),
    EmojiEntry("✅", listOf("check", "done", "yes")),
    EmojiEntry("❌", listOf("cross", "no", "wrong")),
    EmojiEntry("❓", listOf("question")),
    EmojiEntry("❗", listOf("exclamation", "important")),
    EmojiEntry("⏸️", listOf("pause", "break")),
    EmojiEntry("⏰", listOf("alarm", "clock", "time")),
    EmojiEntry("⏳", listOf("hourglass", "wait", "time")),
    EmojiEntry("🔔", listOf("bell", "notification")),
    EmojiEntry("🚭", listOf("no smoking", "quit")),
    EmojiEntry("🚬", listOf("cigarette", "smoke")),
    // Drinks & food
    EmojiEntry("☕", listOf("coffee", "cafe", "tea")),
    EmojiEntry("🫖", listOf("tea", "teapot")),
    EmojiEntry("🍵", listOf("tea", "matcha", "green tea")),
    EmojiEntry("🧉", listOf("mate", "drink")),
    EmojiEntry("🥤", listOf("soda", "drink", "cup")),
    EmojiEntry("🧃", listOf("juice", "box")),
    EmojiEntry("🍺", listOf("beer", "alcohol", "pint")),
    EmojiEntry("🍻", listOf("beers", "cheers", "alcohol")),
    EmojiEntry("🍷", listOf("wine", "alcohol")),
    EmojiEntry("🥂", listOf("champagne", "cheers", "celebrate")),
    EmojiEntry("🍸", listOf("cocktail", "martini", "alcohol")),
    EmojiEntry("🍹", listOf("cocktail", "tropical", "drink")),
    EmojiEntry("🥃", listOf("whiskey", "whisky", "alcohol")),
    EmojiEntry("🍾", listOf("champagne", "bottle", "celebrate")),
    EmojiEntry("🍔", listOf("burger", "food", "fast food")),
    EmojiEntry("🍟", listOf("fries", "food")),
    EmojiEntry("🍕", listOf("pizza", "food")),
    EmojiEntry("🌭", listOf("hot dog", "food")),
    EmojiEntry("🥪", listOf("sandwich", "food")),
    EmojiEntry("🌮", listOf("taco", "food")),
    EmojiEntry("🍿", listOf("popcorn", "movie", "snack")),
    EmojiEntry("🍫", listOf("chocolate", "sweet")),
    EmojiEntry("🍬", listOf("candy", "sweet")),
    EmojiEntry("🍩", listOf("donut", "sweet")),
    EmojiEntry("🍪", listOf("cookie", "sweet")),
    EmojiEntry("🍰", listOf("cake", "dessert", "sweet")),
    EmojiEntry("🎂", listOf("birthday", "cake")),
    EmojiEntry("🍦", listOf("ice cream", "dessert")),
    EmojiEntry("🍎", listOf("apple", "fruit")),
    EmojiEntry("🍌", listOf("banana", "fruit")),
    EmojiEntry("🍇", listOf("grapes", "fruit")),
    EmojiEntry("🍽️", listOf("meal", "dinner", "plate", "food", "after meal")),
    EmojiEntry("🍴", listOf("fork", "knife", "eat")),
    EmojiEntry("🥄", listOf("spoon")),
    // Activities & sport
    EmojiEntry("⚽", listOf("soccer", "football", "sport")),
    EmojiEntry("🏀", listOf("basketball", "sport")),
    EmojiEntry("🏈", listOf("football", "sport")),
    EmojiEntry("🎾", listOf("tennis", "sport")),
    EmojiEntry("🏋️", listOf("gym", "workout", "lift", "exercise")),
    EmojiEntry("🏃", listOf("run", "running", "exercise")),
    EmojiEntry("🚶", listOf("walk", "walking")),
    EmojiEntry("🧘", listOf("yoga", "meditate", "calm", "relax")),
    EmojiEntry("🚴", listOf("bike", "cycling", "exercise")),
    EmojiEntry("🏊", listOf("swim", "pool")),
    EmojiEntry("🎮", listOf("game", "gaming", "controller", "videogame")),
    EmojiEntry("🕹️", listOf("joystick", "game", "arcade")),
    EmojiEntry("🎧", listOf("music", "headphones", "listen")),
    EmojiEntry("🎵", listOf("music", "note", "song")),
    EmojiEntry("🎸", listOf("guitar", "music")),
    EmojiEntry("🎬", listOf("movie", "film", "cinema")),
    EmojiEntry("📺", listOf("tv", "television", "watch")),
    EmojiEntry("📖", listOf("book", "read", "study")),
    EmojiEntry("📚", listOf("books", "study", "read")),
    EmojiEntry("🎨", listOf("art", "paint", "draw", "hobby")),
    EmojiEntry("🎉", listOf("party", "celebrate", "tada")),
    EmojiEntry("🎊", listOf("confetti", "party", "celebrate")),
    EmojiEntry("🛒", listOf("shopping", "cart", "groceries")),
    EmojiEntry("🛍️", listOf("shopping", "bags")),
    // People & social
    EmojiEntry("👥", listOf("people", "social", "group", "friends")),
    EmojiEntry("👫", listOf("couple", "friends", "social")),
    EmojiEntry("🧑‍🤝‍🧑", listOf("friends", "social", "together")),
    EmojiEntry("💬", listOf("chat", "talk", "message", "social")),
    EmojiEntry("📞", listOf("phone", "call")),
    EmojiEntry("📱", listOf("phone", "mobile", "scroll", "social media")),
    EmojiEntry("💻", listOf("laptop", "work", "computer")),
    EmojiEntry("🖥️", listOf("computer", "desktop", "work")),
    EmojiEntry("⌨️", listOf("keyboard", "type", "work")),
    EmojiEntry("💼", listOf("work", "briefcase", "job", "business")),
    EmojiEntry("📈", listOf("chart", "up", "growth", "work")),
    EmojiEntry("📉", listOf("chart", "down", "loss")),
    EmojiEntry("💰", listOf("money", "cash", "cost")),
    EmojiEntry("💸", listOf("money", "spend", "flying")),
    EmojiEntry("🧠", listOf("brain", "mind", "think", "mental")),
    EmojiEntry("🫁", listOf("lungs", "breathe", "health")),
    EmojiEntry("🦷", listOf("tooth", "teeth", "health")),
    EmojiEntry("💪", listOf("muscle", "strong", "power")),
    EmojiEntry("🙏", listOf("pray", "please", "thanks", "hope")),
    EmojiEntry("👍", listOf("thumbs up", "yes", "good")),
    EmojiEntry("👎", listOf("thumbs down", "no", "bad")),
    EmojiEntry("👏", listOf("clap", "applause")),
    EmojiEntry("🤞", listOf("fingers crossed", "hope", "luck")),
    // Places, travel, home
    EmojiEntry("🏠", listOf("home", "house")),
    EmojiEntry("🏡", listOf("home", "house", "garden")),
    EmojiEntry("🏢", listOf("office", "work", "building")),
    EmojiEntry("🏥", listOf("hospital", "health")),
    EmojiEntry("🏫", listOf("school", "study")),
    EmojiEntry("🛏️", listOf("bed", "sleep", "bedroom")),
    EmojiEntry("🚿", listOf("shower", "bathroom", "morning")),
    EmojiEntry("🚽", listOf("toilet", "bathroom")),
    EmojiEntry("🛋️", listOf("couch", "sofa", "relax", "living room")),
    EmojiEntry("🚗", listOf("car", "drive", "driving", "commute")),
    EmojiEntry("🚕", listOf("taxi", "cab")),
    EmojiEntry("🚌", listOf("bus", "commute")),
    EmojiEntry("🚆", listOf("train", "commute")),
    EmojiEntry("✈️", listOf("plane", "flight", "travel")),
    EmojiEntry("🏖️", listOf("beach", "vacation", "relax")),
    EmojiEntry("⛽", listOf("gas", "fuel", "station")),
    EmojiEntry("🚦", listOf("traffic", "light", "commute")),
    // Nature & weather
    EmojiEntry("☀️", listOf("sun", "sunny", "morning")),
    EmojiEntry("🌤️", listOf("sun", "cloud", "weather")),
    EmojiEntry("☁️", listOf("cloud", "weather")),
    EmojiEntry("🌧️", listOf("rain", "weather", "rainy")),
    EmojiEntry("⛈️", listOf("storm", "thunder", "weather")),
    EmojiEntry("❄️", listOf("snow", "cold", "winter")),
    EmojiEntry("🌙", listOf("moon", "night", "evening")),
    EmojiEntry("⭐", listOf("star", "night", "sky")),
    EmojiEntry("🌊", listOf("wave", "ocean", "sea")),
    EmojiEntry("🌱", listOf("plant", "sprout", "grow")),
    EmojiEntry("🌳", listOf("tree", "nature", "park")),
    EmojiEntry("🌸", listOf("blossom", "flower", "spring")),
    EmojiEntry("🌈", listOf("rainbow", "hope")),
    EmojiEntry("🐶", listOf("dog", "pet")),
    EmojiEntry("🐱", listOf("cat", "pet")),
    EmojiEntry("☕", listOf("break", "pause", "rest")),
)

/** Case-insensitive keyword/glyph search over [EmojiCatalog]; blank query returns everything. */
fun searchEmojis(query: String): List<EmojiEntry> {
    val q = query.trim().lowercase()
    if (q.isEmpty()) return EmojiCatalog
    return EmojiCatalog.filter { entry ->
        entry.emoji == query.trim() || entry.keywords.any { it.contains(q) }
    }
}
