default_platform(:android)

platform :android do
  desc "Deploy the production release to Google Play Store open testing tracks"
  lane :deploy_playstore do |options|
    common_upload_options = {
      release_status: "completed",                       # Marks the release as final.
      timeout: 600,                                      # Timeout for the upload process (in seconds).
      json_key: "playstore.credentials.json",            # Path to the service account JSON key.
      package_name: "com.feragusper.smokeanalytics",     # The package name of the application.
      skip_upload_apk: true
    }

    upload_to_play_store(
      common_upload_options.merge(
        track: "wear:beta",
        aab: "apps/wear/build/outputs/bundle/productionRelease/wear-production-release.aab"
      )
    )

    upload_to_play_store(
      common_upload_options.merge(
        track: "beta",
        aab: "apps/mobile/build/outputs/bundle/productionRelease/mobile-production-release.aab"
      )
    )
  end
end
