default_platform(:android)

platform :android do
    desc "Deploy to Play Store"
    lane :deploy_playstore do |options|
        upload_to_play_store(
            release_status: "completed",
            track: "beta",
            timeout: 600,
            json_key: "playstore.credentials.json",
            package_name: "com.feragusper.smokeanalytics",
            aab: "app/build/outputs/bundle/productionRelease/app-production-release.aab"
        )
    end
end
