name: Android CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run tests and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Config keys
        env:
          GOOGLE_AUTH_SERVER_CLIENT_ID: ${{ secrets.GOOGLE_AUTH_SERVER_CLIENT_ID }}
        run: |
          echo google.auth.server.client.id=\"GOOGLE_AUTH_SERVER_CLIENT_ID\" > ./local.properties
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > ./app/google-services.json.asc
          gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch ./app/google-services.json.asc > ./app/google-services.json

      - name: Run tests
        run: bash ./gradlew test --stacktrace

      - name: Run Lint
        run: ./gradlew lint
        continue-on-error: false