# Workflow to build the Android Debug APK and upload the generated artifact
name: Deploy Artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Android Debug APK and Upload Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Configure staging keys and google-services.json
        shell: bash
        env:
          GOOGLE_AUTH_SERVER_CLIENT_ID_STAGING: ${{ secrets.GOOGLE_AUTH_SERVER_CLIENT_ID_STAGING }}
          GOOGLE_AI_CLIENT_GENERATIVEAI_API_KEY_STAGING: ${{ secrets.GOOGLE_AI_CLIENT_GENERATIVEAI_API_KEY_STAGING }}
          GOOGLE_SERVICES_JSON_STAGING: ${{ secrets.GOOGLE_SERVICES_JSON_STAGING }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo google.auth.server.client.id=$GOOGLE_AUTH_SERVER_CLIENT_ID_STAGING > ./local.properties
          echo google.ai.client.generativeai.api.key=$GOOGLE_AI_CLIENT_GENERATIVEAI_API_KEY_STAGING >> ./local.properties

          echo "✅ local.properties configured for staging."

          mkdir -p ./apps/mobile/src/staging/
          echo "$GOOGLE_SERVICES_JSON_STAGING" > ./apps/mobile/src/staging/google-services.json.asc
          gpg -d --passphrase "$GPG_PASSPHRASE" --batch ./apps/mobile/src/staging/google-services.json.asc > ./apps/mobile/src/staging/google-services.json

          if [ ! -s ./apps/mobile/src/staging/google-services.json ]; then
            echo "❌ Decryption failed or file is empty (staging)!"
            exit 1
          fi

          echo "✅ Staging google-services.json decrypted."

      - name: Build Staging Debug APK
        run: ./gradlew assembleStagingDebug --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobile
          path: ./apps/mobile/build/outputs/apk/debug/app-debug.apk
